export const allChores = [
    "Take dishes to kitchen sink after eating",
    "Brush & floss teeth before bed",
    "Bring lunchbox & water bottle to sink",
    "Choose school outfit",
    "Put dirty clothes in hamper",
    "Put away clean laundry in drawers/closets",
    "Brush teeth before school",
    "Rubber bands & brushing after meals",
    "Give guinea pigs food & water",
    "Help pack lunch for school",
    "Put sunblock on face and arms",
    "Independent reading",
    "Put away toys/crafting materials",
    "Make bed",
    "Tidy room",
    "Help make dinner",
    "Help wash dishes",
    "Homework"
  ];